name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  updateDockerImage:
    name: Update Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build -t manukrishnaos/qr-code-generator .

    - name: Push Docker image
      run: docker push manukrishnaos/qr-code-generator

    
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    needs: updateDockerImage

    steps:

    - name: Remote ssh command
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
          sudo docker pull manukrishnaos/qr-code-generator
          sudo docker stop ${{ secrets.DOCKER_CONTAINER_NAME }}
          sudo docker rm ${{ secrets.DOCKER_CONTAINER_NAME }}
          sudo docker run -dt -p ${{ secrets.APP_PORT }}:8000 --name ${{ secrets.DOCKER_CONTAINER_NAME }} manukrishnaos/qr-code-generator
